# 更新 Nginx 配置
$server = "47.108.184.131"
$username = "root"
$password = "Richinfo@123"

# 创建 WinSCP 会话对象
Add-Type -Path "C:\WinSCP\WinSCPnet.dll"

# 设置会话选项
$sessionOptions = New-Object WinSCP.SessionOptions
$sessionOptions.Protocol = [WinSCP.Protocol]::Sftp
$sessionOptions.HostName = $server
$sessionOptions.UserName = $username
$sessionOptions.Password = $password
$sessionOptions.GiveUpSecurityAndAcceptAnySshHostKey = $true

$session = New-Object WinSCP.Session

try {
    # 连接
    $session.Open($sessionOptions)
    Write-Host "连接成功!"
    
    # 备份原配置
    $session.ExecuteCommand("cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak")
    
    # 更新配置
    $newConfig = @'
# Default server configuration
#
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	# SSL configuration
	#
	# listen 443 ssl default_server;
	# listen [::]:443 ssl default_server;
	#
	# Note: You should disable gzip for SSL traffic.
	# See: https://bugs.debian.org/773332
	#
	# Read up on ssl_ciphers to ensure a secure configuration.
	# See: https://bugs.debian.org/765782
	#
	# Self signed certs generated by the ssl-cert package
	# Don't use them in a production server!
	#
	# include snippets/snakeoil.conf;

	root /var/www/cheng-yan-operation;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	# pass PHP scripts to FastCGI server
	#
	#location ~ \.php$ {
	#	include snippets/fastcgi-php.conf;
	#
		# With php-fpm (or other unix sockets):
	#	fastcgi_pass unix:/run/php/php7.4-fpm.sock;
	#	# With php-cgi (or other tcp sockets):
	#	fastcgi_pass 127.0.0.1:9000;
	#}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	#location ~ /\.ht {
	#	deny all;
	#}
}
'@
    
    # 写入新配置
    $session.PutFiles("nginx-config.conf", "/etc/nginx/sites-available/default").Check()
    
    # 重启 Nginx
    $session.ExecuteCommand("systemctl restart nginx")
    
    Write-Host "Nginx 配置已更新并重启!"
}
catch {
    Write-Host "错误: $($_.Exception.Message)"
}
finally {
    $session.Dispose()
}
